version: "3.9"

# Bridge Network for MC server and any related services
networks:
    bridge-network:
      external:
        name: bridge-network  

# Services definition
services:
    # Minecraft server 
    mc:
        image: "ktkoffroth/spigot-mc:0.6"
        restart: always
        stdin_open: true
        tty: true
        env_file: ./env/mc-variables.env
        networks:
            - bridge-network
        volumes: 
            - ../MC:/root/MC
            - ./scripts:/root/scripts
        ports:
            - "25565:25565"
        entrypoint: /root/scripts/entrypoint.sh
